# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, inputs, stylix, ... }:

let acermodule = config.boot.kernelPackages.callPackage ./../../pkgs/acer-rgb.nix {}; in

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Enables NixLD to be able to run (some) regular binaries.
  programs.nix-ld.enable = true;

  # Use latest kernel.
  boot.kernelPackages = pkgs.linuxPackages_latest;
  
  # Enables my Acer RGB Keyboard to work properly.
  boot.extraModulePackages = [ acermodule ];
  boot.kernelModules = [ "facer" "wmi" "sparse-keymap" "video"];  
  
  # Enables Plymouth, and removes most boot messages.
  boot.plymouth.enable = true;
  boot.initrd.systemd.enable = true;
  boot.consoleLogLevel = 3;
  boot.initrd.verbose = false;
  boot.kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"
      "udev.log_priority=3"
      "rd.systemd.show_status=auto"
      "nvidia-drm.fbdev=1" 
  ];

  # Enables XDG Desktop Portals for permission fixes.
  xdg.portal = { 
  	enable = true;
	extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
  };

  # Enables LUKS2 Encryption for my root partition. 
  # AUTOGENERATED ON INSTALL, DO NOT CHANGE THIS!
  boot.initrd.luks.devices."luks-4b2cceb6-23eb-4e64-a942-7c10baf1fc8f".device = "/dev/disk/by-uuid/4b2cceb6-23eb-4e64-a942-7c10baf1fc8f";
  
  # Define your hostname.
  networking.hostName = "amaterasu";

  # Enable networking with Network Manager.
  networking.networkmanager.enable = true;

  # Enable Bluetooth
  hardware.bluetooth = {
    enable = true; # enables support for Bluetooth
    powerOnBoot = true; # powers up the default Bluetooth controller on boot
    # IDK What this does, but it does allow two controllers to connect at oncetherefore allowing me to play Baldur's Gate 3 Local Splitscreen with my cousin. I'm not removing this :P
    settings = {
      General = {
        Privacy = "device";
        JustWorksRepairing = "always";
        Class = "0x000100";
      };
    };
  };
  
  # Enable X11 for compatibility reasons (and removes XTerm from it)
  services.xserver.enable = true;
  services.xserver.excludePackages = [ pkgs.xterm ];

  # Enables Pipewire for sound support.
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true; # Should already be enabled, just making sure.
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Enables Flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Set your time zone.
  time.timeZone = "America/Fortaleza";

  # Removes the Documentation App (Idk why this is preinstalled anyway :P)
  documentation.nixos.enable = false;

  # Select internationalisation properties.
  i18n.defaultLocale = "pt_BR.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "pt_BR.UTF-8";
    LC_IDENTIFICATION = "pt_BR.UTF-8";
    LC_MEASUREMENT = "pt_BR.UTF-8";
    LC_MONETARY = "pt_BR.UTF-8";
    LC_NAME = "pt_BR.UTF-8";
    LC_NUMERIC = "pt_BR.UTF-8";
    LC_PAPER = "pt_BR.UTF-8";
    LC_TELEPHONE = "pt_BR.UTF-8";
    LC_TIME = "pt_BR.UTF-8";
  };

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "br";
    variant = "";
  };

  # Configure console keymap
  console.keyMap = "br-abnt2";

  # Enables the ZSH shell (configured later by Home Manager)
  programs.zsh.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.ladyhayya = {
    isNormalUser = true;
    description = "Lady Hayya";
    shell = pkgs.zsh;
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [ 
    	nautilus
    ];
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = [
  ];

  # Allow usage of Kitty as terminal in Nautilus
  programs.nautilus-open-any-terminal = {
  	enable = true;
  	terminal = "kitty";
  };
 
  # Enables GVFS to fix bugs on Nautilus.
  services.gvfs.enable = true;

  # Enables Power Profile Daemon and Upower for (basic) perfomance control.
  services.upower.enable = true;
  services.power-profiles-daemon.enable = true;

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true  
 
  # Enables Niri (Unstable) + DankMaterialGreeter
  programs.niri.enable = true;
  programs.niri.package = pkgs.niri-unstable;
  
  # Configures some overlays to Nixpkgs from my flakes.
  nixpkgs.overlays = [ 
  	inputs.niri.overlays.niri 
  	inputs.nix-vscode-extensions.overlays.default
  ];

  # Enables DankMaterialGreeter as a frontend for GreetD.
  programs.dankMaterialShell.greeter = {
    enable = true;
    compositor.name = "niri";
    configHome = "/home/ladyhayya";
    configFiles = [
      "/home/ladyhayya/.config/DankMaterialShell/"
    ];
  };

  # Enables Gnome and GDM for screenmirroring (AKA: Baldur's Gate 3 on Biel's House :P)
  #services.displayManager.gdm.enable = true;
  #services.desktopManager.gnome.enable = true;
  # To disable installing GNOME's suite of applications
  # and only be left with GNOME shell.
  #services.gnome.core-apps.enable = false;
  #services.gnome.core-developer-tools.enable = false;
  #services.gnome.games.enable = false;
  #environment.gnome.excludePackages = with pkgs; [ gnome-tour gnome-user-docs ];

  # Enables Stylix for a unified theming for (pretty much) all apps.
  stylix = {
     enable = true;
     base16Scheme = {
    	base00 = "282828";
    	base01 = "3c3836";
    	base02 = "504945";
    	base03 = "665c54";
    	base04 = "bdae93";
    	base05 = "d5c4a1";
    	base06 = "ebdbb2";
    	base07 = "fbf1c7";
    	base0D = "fb4934"; # Red
    	base09 = "fe8019";
    	base0A = "fabd2f";
    	base0B = "b8bb26";
    	base0C = "8ec07c";
    	base08 = "83a598"; #Blue
    	base0E = "d3869b";
	base0F = "d65d0e";
     };
     # Sets up my cursor theme for all theming engines.
     cursor = {
        name = "Capitaine Cursors (Gruvbox)";
	package = pkgs.capitaine-cursors-themed;
	size = 26;
     };
     iconTheme  = {
	enable = true;
	package = pkgs.gruvbox-plus-icons;
	dark = "Gruvbox-Plus-Dark";
     };
     # Sets my wallpaper using WPaperD :P
     image = ./../../modules/home-manager/assets/gruvy.png;
     polarity = "dark";
     enableReleaseChecks = false;
  };

  # This SHOULD set my user picture. SHOULD
  # TLDR: No, this doesn't. TODO: Fix this.
  system.activationScripts.script.text = ''
      mkdir -p /var/lib/AccountsService/{icons,users}
      cp /home/ladyhayya/.nix-desktop/modules/home-manager/assets/icon.png /var/lib/AccountsService/icons/ladyhayya
      echo -e "[User]\nIcon=/var/lib/AccountsService/icons/ladyhayya\n" > /var/lib/AccountsService/users/ladyhayya

      chown root:root /var/lib/AccountsService/users/ladyhayya
      chmod 0600 /var/lib/AccountsService/users/ladyhayya

      chown root:root /var/lib/AccountsService/icons/ladyhayya
      chmod 0444 /var/lib/AccountsService/icons/ladyhayya
  '';

  # Disables the firewall altogether.
  networking.firewall = {
        enable = true;
  	allowedTCPPortRanges = [ { from = 1714; to = 1764; } ];
  	allowedUDPPortRanges = [ { from = 1714; to = 1764; } ]; 
  };

  services.nextdns = {
    enable = true;
    arguments = [ "-profile" "4a18bf" "-cache-size" "10MB" ];
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "26.05"; # Did you read the comment?

}
