# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, inputs, stylix, ... }:

let 
acermodule = config.boot.kernelPackages.callPackage ./../../pkgs/acer-rgb.nix {}; 
nitrosense = pkgs.callPackage ./../../pkgs/nitrosense.nix {inherit pkgs; };
in

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Enables NixLD to be able to run (some) regular binaries.
  programs.nix-ld.enable = true;

  # Use latest kernel.
  boot.kernelPackages = pkgs.linuxPackages_latest;
  
  # Enables my Acer RGB Keyboard to work properly.
  boot.extraModulePackages = [ acermodule ];
  boot.kernelModules = [ "facer" "wmi" "sparse-keymap" "video"];  
  
  # Enables Plymouth, and removes most boot messages.
  boot.plymouth.enable = true;
  boot.initrd.systemd.enable = true;
  boot.consoleLogLevel = 3;
  boot.initrd.verbose = false;
  boot.kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"
      "udev.log_priority=3"
      "acpi_backlight=native"
      "acpi_osi"
      #"rd.systemd.show_status=auto"
      "nvidia-drm.fbdev=1" 
  ];

  # Enables XDG Desktop Portals for permission fixes.
  xdg.portal = { 
  	enable = true;
	extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
  };

  # Enables LUKS2 Encryption for my root partition. 
  # AUTOGENERATED ON INSTALL, DO NOT CHANGE THIS!
  boot.initrd.luks.devices."luks-4b2cceb6-23eb-4e64-a942-7c10baf1fc8f".device = "/dev/disk/by-uuid/4b2cceb6-23eb-4e64-a942-7c10baf1fc8f";
  
  # Define your hostname.
  networking.hostName = "amaterasu";

  # Enable networking with Network Manager.
  networking.networkmanager.enable = true;

  # Enable Bluetooth
  hardware.bluetooth = {
    enable = true; # enables support for Bluetooth
    powerOnBoot = true; # powers up the default Bluetooth controller on boot
    # IDK What this does, but it does allow two controllers to connect at oncetherefore allowing me to play Baldur's Gate 3 Local Splitscreen with my cousin. I'm not removing this :P
    settings = {
      General = {
        Privacy = "device";
        JustWorksRepairing = "always";
        Class = "0x000100";
      };
    };
  };
  
  # Enable X11 for compatibility reasons (and removes XTerm from it)
  services.xserver.enable = true;
  services.xserver.excludePackages = [ pkgs.xterm ];

  # Enables Pipewire for sound support.
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true; # Should already be enabled, just making sure.
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Enables Flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Set your time zone.
  time.timeZone = "America/Fortaleza";

  # Removes the Documentation App (Idk why this is preinstalled anyway :P)
  documentation.nixos.enable = false;

  # Select internationalisation properties.
  i18n.defaultLocale = "pt_BR.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "pt_BR.UTF-8";
    LC_IDENTIFICATION = "pt_BR.UTF-8";
    LC_MEASUREMENT = "pt_BR.UTF-8";
    LC_MONETARY = "pt_BR.UTF-8";
    LC_NAME = "pt_BR.UTF-8";
    LC_NUMERIC = "pt_BR.UTF-8";
    LC_PAPER = "pt_BR.UTF-8";
    LC_TELEPHONE = "pt_BR.UTF-8";
    LC_TIME = "pt_BR.UTF-8";
  };

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "br";
    variant = "";
  };

  # Configure console keymap
  console.keyMap = "br-abnt2";

  # Enables the ZSH shell (configured later by Home Manager)
  programs.zsh.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.ladyhayya = {
    isNormalUser = true;
    description = "Lady Hayya";
    shell = pkgs.zsh;
    extraGroups = [ "networkmanager" "wheel" "libvirtd" ];
    packages = [
    	pkgs.nautilus
	nitrosense
    ];
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile. 
  # De-facto, this is a list of packages that 
  # A: Don't need a module or B: Are dependencies else something breaks wittout them. 
  environment.systemPackages = with pkgs; [
    dmidecode
    python3
    libglvnd
    nextdns
  ];

  # Enables the AccountDaemon.
  # Minor stuff... but it does allows me to declare my Profile Picture :P.
  services.accounts-daemon.enable = true;

  # Allow usage of Kitty as terminal in Nautilus
  programs.nautilus-open-any-terminal = {
  	enable = true;
  	terminal = "kitty";
  };
 
  # Enables GVFS to fix bugs on Nautilus.
  services.gvfs.enable = true;

  # Enables TLP and Upower for perfomance control.
  services.upower.enable = true;
  services.tlp = {
  	enable = true;
	pd.enable = true;
	settings = {
    	CPU_SCALING_GOVERNOR_ON_AC = "performance";
    	CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
	};
  };

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Enable QEMU/KVM and Virt-Manager.
  virtualisation.libvirtd.enable = true;
  programs.virt-manager.enable = true;
  virtualisation.libvirtd.onBoot = "start";

  # Enables Podman for Distrobox
  virtualisation.podman = {
        enable = true;
  	dockerCompat = true;
  };

  # Enables Niri (Unstable) + DankMaterialGreeter
  programs.niri.enable = true;
  programs.niri.package = pkgs.niri-unstable;
  
  # Configures some overlays to Nixpkgs from my flakes.
  nixpkgs.overlays = [ 
  	inputs.niri.overlays.niri 
  	inputs.nix-vscode-extensions.overlays.default
	(final: prev: {
        vesktop = prev.vesktop.overrideAttrs (old: {
          preBuild = ''
            cp -r ${prev.electron.dist} electron-dist
            chmod -R u+w electron-dist
          '';
          buildPhase = ''
            runHook preBuild

            pnpm build
            pnpm exec electron-builder \
              --dir \
              -c.asarUnpack="**/*.node" \
              -c.electronDist="electron-dist" \
              -c.electronVersion=${prev.electron.version}

            runHook postBuild
          '';
        });
        })
  ];

  # Enables DankMaterialGreeter as a frontend for GreetD.
  programs.dankMaterialShell.greeter = {
    enable = true;
    compositor.name = "niri";
    configHome = "/home/ladyhayya";
    configFiles = [
      "/home/ladyhayya/.config/DankMaterialShell/"
    ];
  };

  # Enables Stylix for a unified theming for (pretty much) all apps.
  stylix = {
     enable = true;
     base16Scheme = {
       	base00 = "#1e1e2e"; # base
  	base01 = "#313244"; # surface0
 	base02 = "#45475a"; # surface1
  	base03 = "#6c7086"; # overlay0
  	base04 = "#a6adc8"; # subtext0
  	base05 = "#cdd6f4"; # text
  	base06 = "#f5e0dc"; # rosewater
  	base07 = "#b4befe"; # lavender
  	base08 = "#f38ba8"; # red
  	base09 = "#fab387"; # peach
  	base0A = "#f9e2af"; # yellow
  	base0B = "#a6e3a1"; # green
  	base0C = "#94e2d5"; # teal
  	base0F = "#89b4fa"; # blue
  	base0E = "#cba6f7"; # mauve
  	base0D = "#f5c2e7"; # pink
     };
     # Sets up my cursor theme for all theming engines.
     cursor = {
        name = "catppuccin-mocha-mauve-cursors";
	package = pkgs.catppuccin-cursors.mochaMauve;
	size = 20;
     };
     icons  = {
	enable = true;
	package = pkgs.catppuccin-papirus-folders.override { flavor = "mocha"; accent = "pink"; };
	dark = "Papirus-Dark";
     };
     # Sets my wallpaper using WPaperD :P
     image = ./../../modules/home-manager/assets/cathy.jpg;
     polarity = "dark";
     enableReleaseChecks = false;
  };

  # This sets my user picture, and autoimports (in theory) my Distrobox Containers.ini.
  system.activationScripts.script.text = ''
    mkdir -p /var/lib/AccountsService/{icons,users}
    cp /home/ladyhayya/.nix-desktop/modules/home-manager/assets/icon.png /var/lib/AccountsService/icons/ladyhayya
    echo -e "[User]\nIcon=/var/lib/AccountsService/icons/ladyhayya\n" > /var/lib/AccountsService/users/ladyhayya
    chown root:root /var/lib/AccountsService/users/ladyhayya
    chmod 0600 /var/lib/AccountsService/users/ladyhayya
    chown root:root /var/lib/AccountsService/icons/ladyhayya
    chmod 0444 /var/lib/AccountsService/icons/ladyhayya
  '';

  # Disables the firewall altogether.
  networking.firewall = {
        enable = true;
  	allowedTCPPortRanges = [ { from = 1714; to = 1764; } ];
  	allowedUDPPortRanges = [ { from = 1714; to = 1764; } ]; 
  };

  # Enables NextDNS and configures the profile.
  services.nextdns = {
    enable = true;
    arguments = [ "-profile" "4a18bf" "-cache-size" "10MB" ];
  };

  # Setups a script to automate NextDNS activation.
  systemd.services.nextdns-activate = {
    script = ''
      /run/current-system/sw/bin/nextdns activate
    '';
    after = [ "nextdns.service" ];
    wantedBy = [ "multi-user.target" ];
  };

  # Replaces the (broken) Niri-Flake polkit with a functional Gnome Polkit.
  systemd.user.services.niri-flake-polkit.enable = false;
  security.polkit.enable = true;
  systemd.user.services.polkit-gnome-authentication-agent-1 = {
  description = "polkit-gnome-authentication-agent-1";
  wantedBy = [ "graphical-session.target" ];
  wants = [ "graphical-session.target" ];
  after = [ "graphical-session.target" ];
  serviceConfig = {
    Type = "simple";
    ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
    Restart = "on-failure";
    RestartSec = 1;
    TimeoutStopSec = 10;
  };
  };
  
  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "26.05"; # Did you read the comment?

}
