# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ec230339-7e1d-459a-a80f-97dd33f4372c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ec230339-7e1d-459a-a80f-97dd33f4372c".device = "/dev/disk/by-uuid/ec230339-7e1d-459a-a80f-97dd33f4372c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F7FE-B45D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a1ebd2f4-5f33-406f-8332-e9ba10c584e1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
